version: "3.8"

services:
  spring-boot-liquibase-psql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-boot-liquibase
